spring:
  # 数据源配置
  datasource:
    # mybatisplus 数据源配置
    mybatisplus:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.131.130:3306/quartz_demo?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: root

# mybatisplus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml